events { }

http {
    resolver 127.0.0.11 valid=5s;

    upstream my_servers {
        server senior_engineer_lab-0:80;
        server senior_engineer_lab-1:80;
        server senior_engineer_lab-2:80;
    }

    server {
        listen 80;
        location / {
            set $target http://my_servers;
            proxy_pass $target;
        }
    }
}
